### ISSUE TITLE
Functional Navigation

### ISSUE THREAD

**Issue by jgtaylor** [jgtaylor/octo-vue#1]
## Functional navigation is required.

i like tabs and things on top. I think I have working navigation in commit 48a9047.
- [ ] Landing Page
- [x] General Navigation
- [ ] Some reasonable art/images
- [ ] Get & set a color scheme. -- some colors might be: 
![image](https://user-images.githubusercontent.com/12651312/33495799-176f4268-d6c8-11e7-8b00-baf0a74de9b8.png) OR 
![image](https://user-images.githubusercontent.com/12651312/33495826-35858c4e-d6c8-11e7-8973-20c78e15a7b3.png)

**Comment by jgtaylor** [comment]
```css
/* CSS - Cascading Style Sheet */
/* Palette color codes */
/* Palette URL: http://paletton.com/#uid=72M0X0kbRt14+E48dwffUpTkImm */

/* Feel free to copy&paste color codes to your application */


/* As hex codes */

.color-primary-0 { color: #82BF78 }	/* Main Primary color */
.color-primary-1 { color: #C1DFBD }
.color-primary-2 { color: #A4D39D }
.color-primary-3 { color: #61AB56 }
.color-primary-4 { color: #419334 }

.color-secondary-1-0 { color: #66789A }	/* Main Secondary color (1) */
.color-secondary-1-1 { color: #A6B0C2 }
.color-secondary-1-2 { color: #8391AA }
.color-secondary-1-3 { color: #4C6189 }
.color-secondary-1-4 { color: #314A76 }

.color-secondary-2-0 { color: #E7C992 }	/* Main Secondary color (2) */
.color-secondary-2-1 { color: #FFF1D7 }
.color-secondary-2-2 { color: #FFE8BE }
.color-secondary-2-3 { color: #CEAA68 }
.color-secondary-2-4 { color: #B28A3F }

.color-complement-0 { color: #E18E94 }	/* Main Complement color */
.color-complement-1 { color: #FAD3D6 }
.color-complement-2 { color: #F9B9BD }
.color-complement-3 { color: #C9656C }
.color-complement-4 { color: #AE3D45 }



/* As RGBa codes */

.rgba-primary-0 { color: rgba(130,191,120,1) }	/* Main Primary color */
.rgba-primary-1 { color: rgba(193,223,189,1) }
.rgba-primary-2 { color: rgba(164,211,157,1) }
.rgba-primary-3 { color: rgba( 97,171, 86,1) }
.rgba-primary-4 { color: rgba( 65,147, 52,1) }

.rgba-secondary-1-0 { color: rgba(102,120,154,1) }	/* Main Secondary color (1) */
.rgba-secondary-1-1 { color: rgba(166,176,194,1) }
.rgba-secondary-1-2 { color: rgba(131,145,170,1) }
.rgba-secondary-1-3 { color: rgba( 76, 97,137,1) }
.rgba-secondary-1-4 { color: rgba( 49, 74,118,1) }

.rgba-secondary-2-0 { color: rgba(231,201,146,1) }	/* Main Secondary color (2) */
.rgba-secondary-2-1 { color: rgba(255,241,215,1) }
.rgba-secondary-2-2 { color: rgba(255,232,190,1) }
.rgba-secondary-2-3 { color: rgba(206,170,104,1) }
.rgba-secondary-2-4 { color: rgba(178,138, 63,1) }

.rgba-complement-0 { color: rgba(225,142,148,1) }	/* Main Complement color */
.rgba-complement-1 { color: rgba(250,211,214,1) }
.rgba-complement-2 { color: rgba(249,185,189,1) }
.rgba-complement-3 { color: rgba(201,101,108,1) }
.rgba-complement-4 { color: rgba(174, 61, 69,1) }



/* Generated by Paletton.com Â© 2002-2014 */
/* http://paletton.com */
```
